[2022-02-12 14:53:27,848] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2022-02-12T17:53:19.523647+00:00 [queued]>
[2022-02-12 14:53:27,866] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_3 2022-02-12T17:53:19.523647+00:00 [queued]>
[2022-02-12 14:53:27,867] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 14:53:27,867] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-02-12 14:53:27,870] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 14:53:27,908] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_3> on 2022-02-12T17:53:19.523647+00:00
[2022-02-12 14:53:27,917] {standard_task_runner.py:52} INFO - Started process 15148 to run task
[2022-02-12 14:53:27,947] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_3', '2022-02-12T17:53:19.523647+00:00', '--job-id', '14', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_process.py', '--cfg-path', '/tmp/tmpitgu1qwb', '--error-file', '/tmp/tmpiw12v2ln']
[2022-02-12 14:53:27,948] {standard_task_runner.py:77} INFO - Job 14: Subtask task_3
[2022-02-12 14:53:28,073] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_3 2022-02-12T17:53:19.523647+00:00 [running]> on host ALE-LAPTOP.localdomain
[2022-02-12 14:53:28,173] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2022-02-12T17:53:19.523647+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-12T17:53:19.523647+00:00
[2022-02-12 14:53:28,175] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-02-12 14:53:28,176] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-02-12 14:53:28,186] {subprocess.py:75} INFO - Output:
[2022-02-12 14:53:31,189] {subprocess.py:83} INFO - Command exited with return code 0
[2022-02-12 14:53:31,281] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_3, execution_date=20220212T175319, start_date=20220212T175327, end_date=20220212T175331
[2022-02-12 14:53:31,436] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-12 14:53:31,456] {local_task_job.py:151} INFO - Task exited with return code 0
