[2022-02-12 14:53:21,314] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2022-02-12T17:53:19.523647+00:00 [queued]>
[2022-02-12 14:53:21,347] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2022-02-12T17:53:19.523647+00:00 [queued]>
[2022-02-12 14:53:21,348] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 14:53:21,348] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-02-12 14:53:21,353] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 14:53:21,391] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2022-02-12T17:53:19.523647+00:00
[2022-02-12 14:53:21,402] {standard_task_runner.py:52} INFO - Started process 14912 to run task
[2022-02-12 14:53:21,419] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2022-02-12T17:53:19.523647+00:00', '--job-id', '12', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_process.py', '--cfg-path', '/tmp/tmp4gtac8ve', '--error-file', '/tmp/tmpeqzrvny5']
[2022-02-12 14:53:21,420] {standard_task_runner.py:77} INFO - Job 12: Subtask task_1
[2022-02-12 14:53:21,613] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2022-02-12T17:53:19.523647+00:00 [running]> on host ALE-LAPTOP.localdomain
[2022-02-12 14:53:21,889] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2022-02-12T17:53:19.523647+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-12T17:53:19.523647+00:00
[2022-02-12 14:53:21,901] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-02-12 14:53:21,903] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-02-12 14:53:21,947] {subprocess.py:75} INFO - Output:
[2022-02-12 14:53:24,951] {subprocess.py:83} INFO - Command exited with return code 0
[2022-02-12 14:53:25,223] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20220212T175319, start_date=20220212T175321, end_date=20220212T175325
[2022-02-12 14:53:25,612] {taskinstance.py:1245} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2022-02-12 14:53:25,685] {local_task_job.py:151} INFO - Task exited with return code 0
