[2022-02-12 14:53:33,074] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2022-02-12T17:53:19.523647+00:00 [queued]>
[2022-02-12 14:53:33,193] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_4 2022-02-12T17:53:19.523647+00:00 [queued]>
[2022-02-12 14:53:33,194] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 14:53:33,194] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-02-12 14:53:33,199] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 14:53:33,308] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_4> on 2022-02-12T17:53:19.523647+00:00
[2022-02-12 14:53:33,336] {standard_task_runner.py:52} INFO - Started process 15355 to run task
[2022-02-12 14:53:33,387] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_4', '2022-02-12T17:53:19.523647+00:00', '--job-id', '15', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_process.py', '--cfg-path', '/tmp/tmpe118prip', '--error-file', '/tmp/tmppz9bexy5']
[2022-02-12 14:53:33,394] {standard_task_runner.py:77} INFO - Job 15: Subtask task_4
[2022-02-12 14:53:33,563] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_4 2022-02-12T17:53:19.523647+00:00 [running]> on host ALE-LAPTOP.localdomain
[2022-02-12 14:53:33,864] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_4
AIRFLOW_CTX_EXECUTION_DATE=2022-02-12T17:53:19.523647+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-12T17:53:19.523647+00:00
[2022-02-12 14:53:33,879] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-02-12 14:53:33,881] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-02-12 14:53:33,922] {subprocess.py:75} INFO - Output:
[2022-02-12 14:53:36,932] {subprocess.py:83} INFO - Command exited with return code 0
[2022-02-12 14:53:37,409] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_4, execution_date=20220212T175319, start_date=20220212T175333, end_date=20220212T175337
[2022-02-12 14:53:37,689] {taskinstance.py:1245} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-02-12 14:53:37,732] {local_task_job.py:151} INFO - Task exited with return code 0
