[2022-02-12 14:01:13,143] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2022-02-12T17:01:08.870598+00:00 [queued]>
[2022-02-12 14:01:13,238] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_1 2022-02-12T17:01:08.870598+00:00 [queued]>
[2022-02-12 14:01:13,238] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 14:01:13,239] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-02-12 14:01:13,242] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 14:01:13,294] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_1> on 2022-02-12T17:01:08.870598+00:00
[2022-02-12 14:01:13,302] {standard_task_runner.py:52} INFO - Started process 4433 to run task
[2022-02-12 14:01:13,319] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_1', '2022-02-12T17:01:08.870598+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_process.py', '--cfg-path', '/tmp/tmp2o0kfls7', '--error-file', '/tmp/tmpc62en9k2']
[2022-02-12 14:01:13,328] {standard_task_runner.py:77} INFO - Job 5: Subtask task_1
[2022-02-12 14:01:13,483] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_1 2022-02-12T17:01:08.870598+00:00 [running]> on host ALE-LAPTOP.localdomain
[2022-02-12 14:01:13,626] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_1
AIRFLOW_CTX_EXECUTION_DATE=2022-02-12T17:01:08.870598+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-12T17:01:08.870598+00:00
[2022-02-12 14:01:13,628] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-02-12 14:01:13,629] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-02-12 14:01:13,637] {subprocess.py:75} INFO - Output:
[2022-02-12 14:01:16,645] {subprocess.py:83} INFO - Command exited with return code 0
[2022-02-12 14:01:16,959] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_1, execution_date=20220212T170108, start_date=20220212T170113, end_date=20220212T170116
[2022-02-12 14:01:17,138] {taskinstance.py:1245} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2022-02-12 14:01:17,190] {local_task_job.py:151} INFO - Task exited with return code 0
