[2022-02-12 14:01:06,942] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2022-02-11T00:00:00+00:00 [queued]>
[2022-02-12 14:01:06,998] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: parallel_dag.task_2 2022-02-11T00:00:00+00:00 [queued]>
[2022-02-12 14:01:06,999] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 14:01:06,999] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2022-02-12 14:01:07,001] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2022-02-12 14:01:07,027] {taskinstance.py:1087} INFO - Executing <Task(BashOperator): task_2> on 2022-02-11T00:00:00+00:00
[2022-02-12 14:01:07,035] {standard_task_runner.py:52} INFO - Started process 4050 to run task
[2022-02-12 14:01:07,055] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'parallel_dag', 'task_2', '2022-02-11T00:00:00+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/parallel_process.py', '--cfg-path', '/tmp/tmp5fzy2ysm', '--error-file', '/tmp/tmpm64t9g2q']
[2022-02-12 14:01:07,061] {standard_task_runner.py:77} INFO - Job 4: Subtask task_2
[2022-02-12 14:01:07,243] {logging_mixin.py:104} INFO - Running <TaskInstance: parallel_dag.task_2 2022-02-11T00:00:00+00:00 [running]> on host ALE-LAPTOP.localdomain
[2022-02-12 14:01:07,535] {taskinstance.py:1282} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=parallel_dag
AIRFLOW_CTX_TASK_ID=task_2
AIRFLOW_CTX_EXECUTION_DATE=2022-02-11T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-11T00:00:00+00:00
[2022-02-12 14:01:07,537] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-02-12 14:01:07,538] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'sleep 3']
[2022-02-12 14:01:07,561] {subprocess.py:75} INFO - Output:
[2022-02-12 14:01:10,568] {subprocess.py:83} INFO - Command exited with return code 0
[2022-02-12 14:01:11,046] {taskinstance.py:1191} INFO - Marking task as SUCCESS. dag_id=parallel_dag, task_id=task_2, execution_date=20220211T000000, start_date=20220212T170106, end_date=20220212T170111
[2022-02-12 14:01:11,388] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-12 14:01:11,449] {local_task_job.py:151} INFO - Task exited with return code 0
